### ISSUE TITLE
Cashaddr prefix input problem

### ISSUE THREAD

**Issue by imaginaryusername** [rt121212121/electron_cash_scheduled_payments_plugin#1]
When using the plugin with the cashaddr format, with prefix the input box returns a 
```
Invalid bitcoincash URI:
'PaymentDialog' object has no attribute 'on_p'  
```

error and proceeds to disallow creating a recurring payment. Removing the prefix seems to allow creation as expected.

**Comment by rt121212121** [comment]
Fixed in b66eef86e98d7ea862bc05ecc19e866e81ab294f
